##Based on code generated by Peter Breslin (ASU) and Fabio Suzart de Albuquerque 

######################################################################
########################### Libraries ################################
######################################################################

library(raster)
library(sp)
library(sf)
library(rworldmap)
library(rgdal)
library(spdep)
library(rgeos)
library(dismo)
library(gbm)
library(AUC)
library(ggplot2)
library(plyr)
library(HH)
library(ltm)
library(geosphere)

##load data points
setwd("G:\\Shared drives\\Emily_Schumacher\\SDMs")

##Load in data file without autocorrelation
butternut_pres <- read.csv("InputFiles\\Points\\occurrence_no_auto_noproj.csv")
butternut_pres <- butternut_pres[,-1]

##calculate crop limits
min_lon <- min(butternut_pres$Longitude)
max_lon <- max(butternut_pres$Longitude)
min_lat <- min(butternut_pres$Latitude)
max_lat <- max(butternut_pres$Latitude)

##spatial code 
coordinates(butternut_pres) <- c('Longitude', 'Latitude')
proj4string(butternut_pres) <- CRS("+proj=longlat +ellps=WGS84 +datum=WGS84")

##Projection
projection <- c("+proj=aea +lat_1=20 +lat_2=60 +lat_0=40 +lon_0=-96 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs")

######################################################################
################## Generate Pseudo-Absence Points ####################
######################################################################
##Create extent raster
extent_raster <- raster(ncol = 100, nrow = 100,xmn=min_lon,xmx=max_lon,ymn=min_lat,ymx=max_lat)

##load in elevation raster
elev_raster <- raster("InputFiles\\wc2.1_2.5m_elev.tif")

##crop raster
elev_crop <- crop(elev_raster, extent_raster)

##project
extent_project <- projectRaster(elev_crop, crs = paste0(projection))

##write out raster
writeRaster(extent_project, "InputFiles\\extent_project.tif")

##Now project presence points
pres_proj <- spTransform(butternut_pres, CRS(paste0(projection)))

##validating aligning projetion
pres_ext <- extract(extent_project, pres_proj)
pres_ext_df <- data.frame(pres_ext)
pres_points_df <- data.frame(pres_proj)

pres_df <- cbind(pres_points_df, pres_ext_df)
pres_df <- na.omit(pres_df)

##write out presence clean 
write.csv(pres_df[,-3], "InputFiles\\Points\\pres_clean_df.csv")

##presence clean spatial
coordinates(pres_df) <- c('Longitude', 'Latitude')
proj4string(pres_df) <- CRS(paste0(projection))

plot(extent_project)
points(pres_df)

##Now start generating background points
background_points <- randomPoints(extent_project, 5712)

##now continue to sample
set.seed(25)
background_2 <- gridSample(background_points, extent_project, n=1) 
bg_proj <- SpatialPoints(background_2, proj4string=CRS(paste0(projection)))

##now set occurrence records to a spatial gridded object
set.seed(8)
extent_sample <- gridSample(pres_df, extent_project, n=1) 

##turn into a spatial points object
occurrence_grid_spatial <-SpatialPoints(extent_sample, CRS(paste0(projection)))

##determine the difference between absence and presence to make sure they aren't in the same place 
butternut_abs <- gDifference(bg_proj, occurrence_grid_spatial)

##plot to determine if anything is outside our bounds
plot(extent_project)
points(butternut_abs)

##extract to points to make sure data is clean
abs_ext <- extract(extent_project, butternut_abs)
abs_ext_df <- data.frame(abs_ext)
abs_ext_df <- na.omit(abs_ext_df)

##no na points, good to go
##Butternut absence data frame
butternut_abs_df <- data.frame(butternut_abs)

##write out absence 
write.csv(butternut_abs_df, "InputFiles\\Points\\butternut_abs_df_proj.csv")

##Now rename columns and set up data frame
col_names <- colnames(pres_points_df)

colnames(butternut_abs_df) <- col_names

##Prepare presence and absence records
##Absence column added 
butternut_abs_df$PA <- "0"

##Add presence column to presence points
pres_points_df$PA <- "1"

##combine into one data frame
butternut_pa <- rbind(pres_points_df, butternut_abs_df)

##Write out files 
write.csv(butternut_pa, "InputFiles\\Points\\butternut_pa_clean.csv")

##
pdf("InputFiles\\pres_abs_points.pdf", width = 6, height = 6)
plot(extent_project)
points(butternut_abs, pch = 16, col = "dodgerblue4")
points(butternut_pres_proj, pch = 16, col = "dodgerblue")
legend('topright', legend = c("Presence", "Absence"), pch = 16, col = c("dodgerblue", "dodgerblue4"))
dev.off()
