##Based on code generated by Peter Breslin (ASU) and Fabio Suzart de Albuquerque 

######################################################################
########################### Libraries ################################
######################################################################

library(raster)
library(sp)
library(sf)
library(rworldmap)
library(rgdal)
library(spdep)
library(rgeos)
library(dismo)
library(gbm)
library(AUC)
library(ggplot2)
library(plyr)
library(HH)
library(ltm)
library(geosphere)

##load data points
setwd("G:\\Shared drives\\Emily_Schumacher\\SDMs")

##Projection
projection <- c("+proj=aea +lat_1=20 +lat_2=60 +lat_0=40 +lon_0=-96 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs")

######################################################################
####################### Running the Model ############################
######################################################################
##load in variable data frame
worldclim_only <- "G:\\Shared drives\\Emily_Schumacher\\SDMs\\worldclim_only_SDM\\"
###
butternut_var <- read.csv(paste0(worldclim_only,"butternut_variables.csv"))
butternut_var <- butternut_var[,-1]

##now limit to important variables
##all var - butternut_list_variables <- c("pwetm", "mdr","mtdq", "mtwetq", "precip_season")

butternut_list_variables <- c("pwetm", "mdr","mtdq", "mtwetq", "precip_season")

##now load variables for model running
butternut_sel_var <- butternut_var[,butternut_list_variables]
butternut_sel_df <- cbind(butternut_var[,1:3], butternut_sel_var)
butternut_sel_df[,3] <- as.numeric(butternut_sel_df[,3]) 

##now run models
par(mfrow=c(1,1))
set.seed(10)
butternut_samp <- sample(nrow(butternut_sel_df), round(0.70 * nrow(butternut_sel_df))) 
testdata <- na.omit(butternut_sel_df[butternut_samp,])
traindata <- na.omit(butternut_sel_df[-butternut_samp,])

#Model calibration. Using multiple BRT parameters to identify the best number of trees. See the Elith tutorial on what these parameters mean. 
###there's a bunch of other things but code line 384 is how you do the predictions and generate the map. Most of the other things in here 
####are either in the Elith tutorial or were related to finding range contraction and 
####expansion. 
bf=c(.7)
lr=c(0.07)
tc=c(2)
ss=c(25)
#Initiate the loop to identify the best number of trees. Call your model whatever you want- the "gbm.x = 4:7" are the columns of your climate variables and the "gbm.y=3" is the column on your csv file that has 0's and 1's for presence/absence 
for (i in 1:length(lr)){
  for (j in 1:length(bf)){
    for (k in 1:length(tc)){
      for(l in 1:length(ss)){
        
        
        ##Fit the gbm model
        #create a model name to store in the results table, I removed for (l in 1:length(ss)), ss[l],{ dist[t],'_'and 
        butternut_model_name <- paste('butternut_model_',tc[k],'_',lr[i],'_',bf[j],'_',ss[l],'_',sep='')
        
        set.seed(10)
        butternut_model <- gbm.step(traindata, gbm.x = 4:length(butternut_sel_df), gbm.y = 3, family = "bernoulli", step.size = ss[l],tree.complexity = tc[k],learning.rate = lr[i], bag.fraction = bf[j])
        
        #Model internal metrics 
        cv.AUC = butternut_model$cv.statistics$discrimination.mean 
        cv.dev = butternut_model$cv.statistics$deviance.mean # average residual deviance over all folds during cross-validation 
        
        #Calculate the % of deviance explained. Deviance explained corresponds to the percentage of deviance for the null model explained by the fitted model (dev = 100% for a perfect model)
        #The function calc.deviance() in dismo package calculates the deviance between 2 vectors v 1 and v 2
        #calculating deviance explained by the model over the training dataset (int.dev)
        int.null.deviance = butternut_model$self.statistics$mean.null 
        int.residual.deviance = butternut_model$cv.statistics$deviance.mean 
        int.dev=(int.null.deviance-int.residual.deviance)/int.null.deviance
        pred.train = predict.gbm(butternut_model, traindata, n.trees = butternut_model$gbm.call$best.trees, type = "response") 
        train=calc.deviance(traindata$PA, pred.train)
        
        ##Model external metrics , calculated over an evaluation datasetevaluation.df”      
        pred_test = predict.gbm(butternut_model, testdata, n.trees = butternut_model$gbm.call$best.trees, type = "response") 
        d <- cbind(testdata$PA, pred_test) 
        pres <- d[d[,1]==1, 2]
        abs <- d[d[,1]==0, 2]
        eval <- evaluate(p=pres, a=abs)
        ext.AUC <- eval@auc
        
        #estimating the threshold to convert suitability values into binary maps (0/1)
        th<-eval@t[which.max(eval@TPR + eval@TNR)]
        
        independent=calc.deviance(testdata$PA, pred_test)  
        #residual deviance was calculated between observed presence/absence data (v 1) and predicted probability of presence (v 2 ),
        ext.residual.deviance = calc.deviance(testdata$PA, pred_test, calc.mean=T)
        ext.null.deviance = calc.deviance(testdata$PA,rep(mean(testdata$PA),nrow(testdata)), calc.mean=T) 
        #Calculating deviance explained in the evaluation dataset. Portion of data withheld during model building
        ext.dev=(ext.null.deviance - ext.residual.deviance)/ext.null.deviance
        
        
        df<-rbind(df, data.frame(butternut_model_name,tc[k],lr[i],bf[j],ss[l],butternut_model$gbm.call$best.trees,cv.AUC,ext.AUC,int.dev,ext.dev,train,independent,ext.residual.deviance))
        
      }
    }
  }
}
th


bf=c(.7)
lr=c(0.07)
tc=c(2)
ss=c(25)
#Initiate the loop to identify the best number of trees. Call your model whatever you want- the "gbm.x = 4:7" are the columns of your climate variables and the "gbm.y=3" is the column on your csv file that has 0's and 1's for presence/absence 


##tree number save -- look at red printed text
tree_number <- 1150

##summarize model - percent contribution of each variable
summary(butternut_model)

###
butternut_predictors <- c("Seasonal Precipitation (mm)", "Mean Temperature of the Driest Quarter (C)",
                        "Mean Temperature of the Wettest Quarter (C)", "Precipitation of the Wettest Month (mm)", "Mean Diurnal Range")
butternut_predictors <- factor(butternut_predictors, levels= c("Seasonal Precipitation (mm)", "Mean Temperature of the Driest Quarter (C)",
                                                            "Mean Temperature of the Wettest Quarter (C)", "Precipitation of the Wettest Month (mm)",
                                                            "Mean Diurnal Range"))
butternut_influences <- data.frame(butternut_predictors,percentages=c(29.5, 25.0, 23.7, 11.7, 10.2))

butternut_contribution_bp <- ggplot(data=butternut_influences, aes(x=butternut_predictors, y=percentages)) +
  geom_bar(stat="identity", color="black", fill="dodgerblue",width=.4)+
  geom_text(aes(y=percentages, label=paste0(percentages, '%')), vjust=.5, hjust=-.1,size=3)+
  theme_minimal()+ggtitle("Relative Influence of Predictors (CV AUC = 0.882)")+theme_light(base_size=14)+theme(plot.margin = unit(c(1,1,1,1), "cm"))+ylim(0,100)+
  xlab("Predictors") + ylab("Percent Contribution to the Model")

butternut_contribution_bp2 <- butternut_contribution_bp + coord_flip()

pdf(paste0(worldclim_only,"contribution_bp_allvar.pdf"), width = 10, height = 8)
butternut_contribution_bp2
dev.off()  

#######################
#### Prediction map ###
#######################
##load data stacks
setwd("G:\\Shared drives\\Emily_Schumacher\\SDMs")
##load in elevation crop
elevation_crop <- raster("InputFiles\\elevation_extent.tif")

##load in elevation extent
extent_project <- projectRaster(elevation_crop, crs = projection)

##load in stacks of variables
setwd("G:\\Shared drives\\Emily_Schumacher\\SDMs\\InputFiles\\bio_2-5m_bil")

##create multiple lists
worldclim_list = list.files(pattern = ".bil$")
worldclim_raster_list <- list()
worldclim_crop_list <- list()
worldclim_project_list <- list()

##loop through soil docs to crop and project every layer 
for(j in 1:length(worldclim_list)) {
  #convert to rasters
  worldclim_raster_list[[j]] = raster(paste0("G:\\Shared drives\\Emily_Schumacher\\SDMs\\InputFiles\\bio_2-5m_bil\\", worldclim_list[[j]]))
  
  worldclim_crop_list[[j]] <- crop(worldclim_raster_list[[j]], elevation_crop)
  
  worldclim_project_list[[j]] <- projectRaster(worldclim_crop_list[[j]], crs = projection)
  
}

##Rename layers
worldclim_names <- c("mat", "mtwarq", "mtcq", "map", "pwetm", "pdm", "precip_season",
                     "pwetq", "pdq", "pwarq", "pcq", "mdr","iso","temp_season", 
                     "mtwm","mtcm", "temp_range", "mtwetq", "mtdq")

for(p in 1:length(worldclim_names)) {
  
  names(worldclim_project_list[[p]]) <- worldclim_names[[p]]
  
}

##now create a raster stack of these variables
worldclim_stack <- stack(worldclim_project_list[[1]], worldclim_project_list[[2]],
                         worldclim_project_list[[3]], worldclim_project_list[[4]],
                         worldclim_project_list[[5]], worldclim_project_list[[6]],
                         worldclim_project_list[[7]], worldclim_project_list[[8]],
                         worldclim_project_list[[9]], worldclim_project_list[[10]],
                         worldclim_project_list[[11]], worldclim_project_list[[12]],
                         worldclim_project_list[[13]], worldclim_project_list[[14]],
                         worldclim_project_list[[15]], worldclim_project_list[[16]],
                         worldclim_project_list[[17]], worldclim_project_list[[18]],
                         worldclim_project_list[[19]])

########Now begin to stack variables that contribute most to the model

##to get list of names for ordering stack 
var_list <- butternut_model$var.names

##now stack
butternut_model_stack <- stack(worldclim_stack$pwetm, worldclim_stack$mdr,
                               worldclim_stack$mtdq, worldclim_stack$mtwetq,
                               worldclim_stack$precip_season)
  
  
##Names must be equal to compare 
names(butternut_model_stack) <- butternut_model$var.names

##now create prediction map
butternut_prediction_map <- predict(butternut_model_stack, butternut_model,n.trees=1150, type='response')

setwd(worldclim_only)
##write out Raster
writeRaster(butternut_prediction_map, "hsm_worldclim_only_raster.tif")

##Load in presence and absence points 
butternut_pres <- butternut_sel_df[butternut_sel_df$PA == 1,]
butternut_abs <- butternut_sel_df[butternut_sel_df$PA == 0,]

##create points 
coordinates(butternut_pres) <- c('Longitude', 'Latitude')
proj4string(butternut_pres) <- CRS(projection)

coordinates(butternut_abs) <- c('Longitude', 'Latitude')
proj4string(butternut_abs) <- CRS(projection)

##now look at plots
pdf("hsm.pdf", width = 6, height = 6)
plot(butternut_prediction_map, main = "Habitat Suitability Model")
dev.off()

pdf("hsm_p.pdf", width = 6, height = 6)
plot(butternut_prediction_map, main = "HSM Presence")
points(butternut_pres, col = "dodgerblue", pch = 16)
dev.off()

pdf("hsm_a.pdf", width = 6, height = 6)
plot(butternut_prediction_map, main = "HSM Absence")
points(butternut_abs, col = "dodgerblue4", pch = 16)
dev.off()

pdf("hsm_pa.pdf", width = 6, height = 6)
plot(butternut_prediction_map, main = "HSM Presence and Absence")
points(butternut_abs, col = "dodgerblue4", pch = 16)
points(butternut_pres, col = "dodgerblue", pch = 16)
legend('topright', legend = c("Presence", "Absence"), pch = 16, col = c("dodgerblue", "dodgerblue4"))
dev.off()

##now extract
hsm_p <- extract(butternut_prediction_map, butternut_pres)
hsm_a <- extract(butternut_prediction_map, butternut_abs)

##convert to data frames
hsm_p_df <- data.frame(hsm_p)
hsm_a_df <- data.frame(hsm_a)

colnames(hsm_p_df) <- c("HSM_per")
colnames(hsm_a_df) <- c("HSM_per")

hsm_p_df$PA <- "1"
hsm_a_df$PA <- "0"

##combine into one table
hsm_performance_pa <- rbind(hsm_p_df, hsm_a_df)

hsm_performance_pa <- na.omit(hsm_performance_pa)

##now create a plot to compare 

pdf("hsm_performance.pdf", width = 6, height = 6)
boxplot(hsm_performance_pa[hsm_performance_pa$PA == 1,][,1], hsm_performance_pa[hsm_performance_pa$PA == 0,][,1], names = c("Presence", "Absence"), main = "Presence and Absence Range of Habitat Suitability", ylab = "Percent Habitat Suitability", xlab = "Type of Point", ylim = c(0,1))
dev.off()

##maybe do a t test
wilcox.test(hsm_performance_pa[hsm_performance_pa$PA == 1,][,1], hsm_performance_pa[hsm_performance_pa$PA == 0,][,1])

####Calculate range

##remove points where no value is found
hsm_p_df <- na.omit(hsm_p_df)

##now calculate total length
total_pres <- length(hsm_p_df$HSM_per)

###threshold
((length(hsm_p_df[(hsm_p_df$HSM_per >= 0.6) == TRUE,][,1]))/total_pres)*100

##calculate values for presence
pres_greater_than_half <- ((length(hsm_p_df[(hsm_p_df$HSM_per >= 0.5) == TRUE,][,1]))/total_pres)*100
pres_greater_than_75 <- ((length(hsm_p_df[(hsm_p_df$HSM_per >= 0.75) == TRUE,][,1]))/total_pres)*100
pres_greater_equal_95 <- ((length(hsm_p_df[(hsm_p_df$HSM_per >= 0.95) == TRUE,][,1]))/total_pres)*100

##Calculate full length
hsm_a_df <- na.omit(hsm_a_df)

##Calculate total absences 
total_abs <- length(hsm_a_df$HSM_per)

##Create absence prediction percentages
abs_greater_than_half <- ((length(hsm_a_df[(hsm_a_df$HSM_per >= 0.5) == TRUE,][,1]))/total_abs)*100
abs_greater_than_75 <- ((length(hsm_a_df[(hsm_a_df$HSM_per >= 0.75) == TRUE,][,1]))/total_abs)*100
abs_great_equal_95 <- ((length(hsm_a_df[(hsm_a_df$HSM_per >= 0.95) == TRUE,][,1]))/total_abs)*100

##Create df for performance
performance_matrix <- matrix(nrow = 3, ncol = 2)
colnames(performance_matrix) <- c("Percent_Presence", "Percent_Pseudoabsence")
rownames(performance_matrix) <- c("Greater than or equal to 50% Suitability",
                                  "Greater than or equal to 75% Suitability",
                                  "Greater than or equal to 95% Suitability")

##Load in performance numbers
performance_matrix[,1] <- c(pres_greater_than_half, pres_greater_than_75, pres_greater_equal_95)
performance_matrix[,2] <- c(abs_greater_than_half, abs_greater_than_75, abs_great_equal_95)
performance_matrix <- round(performance_matrix, digits = 1)

##now write out table
write.csv(performance_matrix,"performance_matrix.csv")

######################################################################
########################## LGM and Holocene ##########################
######################################################################
##stack prediction variable layers
worldclim_path <- "G:\\Shared drives\\Emily_Schumacher\\SDMs\\worldclim_only_SDM"

##write out raster
##Load in LGM layers
setwd("G:\\Shared drives\\Emily_Schumacher\\SDMs\\Paleo_Files\\LGM_BCV_2-5m")
pwetm_lgm <- raster("mrlgmbi13.tif")
mdr_lgm <- raster("mrlgmbi2.tif")
mtdq_lgm  <- raster("mrlgmbi9.tif")
mtwetq_lgm <- raster("mrlgmbi8.tif")
precip_season_lgm <- raster("mrlgmbi15.tif")

##now check out stack
var_list 

lgm_stack <- stack(pwetm_lgm, mdr_lgm, mtdq_lgm, mtwetq_lgm,
                   precip_season_lgm)

##now project and crop
lgm_stack_crop <- crop(lgm_stack, elevation_crop)
lgm_stack_project <- projectRaster(lgm_stack_crop, crs = projection)
names(lgm_stack_project) <- butternut_model$var.names

####now create HSM
lgm_hsm <- predict(lgm_stack_project,butternut_model,n.trees=tree_number,type='response')
plot(lgm_hsm)

##write Raster out
writeRaster(lgm_hsm, paste0(worldclim_only, "hsm_lgm.tif"))

pdf(paste0(worldclim_only, "hsm_lgm.pdf"))
plot(lgm_hsm, main = "HSM for butternut at the LGM (22000 YBP)")
dev.off()

###6000 YBP - Mid-Hol
##Load in LGM layers
setwd("G:\\Shared drives\\Emily_Schumacher\\SDMs\\Paleo_Files\\mid_hol")

##look at var list to see stacking order

##load in mid Holocene rasters
pwetm_mid_hol <- raster("mrmidbi13.tif")
mdr_mid_hol <- raster("mrmidbi2.tif")
mtdq_mid_hol <- raster("mrmidbi9.tif")
mtwetq_mid_hol <- raster("mrmidbi8.tif")
precip_season_mid_hol <- raster("mrmidbi15.tif")

###Stack 
mid_hol_stack <- stack(pwetm_mid_hol,mdr_mid_hol,mtdq_mid_hol,
                       mtwetq_mid_hol, precip_season_mid_hol)

##Crop 
mid_hol_stack_crop <- crop(mid_hol_stack, elevation_crop)

##project to raster
mid_hol_project <- projectRaster(mid_hol_stack_crop, crs = projection)

###Mid-Holocene 
names(mid_hol_project) <- var_list

##Now predict 
mid_hol_hsm <- predict(mid_hol_project,butternut_model,
                       n.trees= tree_number,type='response')

##plot the hsm
plot(mid_hol_hsm)

##write out image
pdf(paste0(worldclim_only, "mid_hol_hsm.pdf"))
plot(mid_hol_hsm, main = "Habitat Suitability Model for Butternut in the Mid-Holocene (6000 YBP)")
dev.off()

##now write out raster
writeRaster(mid_hol_hsm, paste0(worldclim_only, "mid_hol_hsm.tif"))

##############LIG
setwd("G:\\Shared drives\\Emily_Schumacher\\SDMs\\Paleo_Files\\LIG_v1_2_5m")
pwetm_lig <- raster("bio_13.tif")
mdr_lig <- raster("bio_2.tif")
mtdq_lig <- raster("bio_9.tif")
mtwetq_lig <- raster("bio_8.tif")
precip_season_lig <- raster("bio_15.tif")

###now stack
var_list
lig_stack <- stack(pwetm_lig, mdr_lig, mtdq_lig,
                   mtwetq_lig, precip_season_lig)
##########
##Crop 
lig_stack_crop <- crop(lig_stack, elevation_crop)

##project to raster
lig_project <- projectRaster(lig_stack_crop, crs = projection)

###Name lig
names(lig_project) <- var_list

##Now predict 
lig_hsm <- predict(lig_project,butternut_model,
                       n.trees= tree_number,type='response')

writeRaster(lig_hsm, "lig_hsm.tif")
writeRaster(lig_hsm > 0.63, "lig_suitability.tif")

###################BA
paleo_path <- "G:\\Shared drives\\Emily_Schumacher\\SDMs\\Paleo_Files"

##setwd 
setwd(paleo_path)

##ok load rasters 
pwetm_ba <- raster("ba_v1_2_5m\\bio_13.tif")
mdr_ba <- raster("ba_v1_2_5m\\bio_2.tif")
mtdq_ba <- raster("ba_v1_2_5m\\bio_9.tif")
mtwetq_ba <- raster("ba_v1_2_5m\\bio_8.tif")
precip_season_ba <- raster("ba_v1_2_5m\\bio_15.tif")

##now stack the rasters
ba_stack <- stack(pwetm_ba, mdr_ba, mtdq_ba, mtwetq_ba, 
                  precip_season_ba)

##Crop 
ba_stack_crop <- crop(ba_stack, elevation_crop)

##project to raster
ba_project <- projectRaster(ba_stack_crop, crs = projection)

###Name ba
names(ba_project) <- var_list

##Now predict 
ba_hsm <- predict(ba_project,butternut_model,
                   n.trees= tree_number,type='response')
##set wd
setwd("G:\\Shared drives\\Emily_Schumacher\\SDMs\\worldclim_only_SDM")

##write out BA HSM 
writeRaster(ba_hsm, "ba_hsm.tif")
writeRaster(ba_hsm > 0.63, "ba_suitability.tif")

############EH
##setwd 
setwd(paleo_path)

##ok load rasters 
pwetm_eh <- raster("eh_v1_2_5m\\bio_13.tif")
mdr_eh <- raster("eh_v1_2_5m\\bio_2.tif")
mtdq_eh <- raster("eh_v1_2_5m\\bio_9.tif")
mtwetq_eh <- raster("eh_v1_2_5m\\bio_8.tif")
precip_season_eh <- raster("eh_v1_2_5m\\bio_15.tif")

##now stack the rasters
eh_stack <- stack(pwetm_eh, mdr_eh, mtdq_eh, mtwetq_eh, 
                  precip_season_eh)

##Crop 
eh_stack_crop <- crop(eh_stack, elevation_crop)

##project to raster
eh_project <- projectRaster(eh_stack_crop, crs = projection)

###Name ba
names(eh_project) <- var_list

##Now predict 
eh_hsm <- predict(eh_project,butternut_model,
                  n.trees= tree_number,type='response')
##set wd
setwd(worldclim_path)

##write out BA HSM 
writeRaster(eh_hsm, "eh_hsm.tif")
writeRaster(eh_hsm > 0.63, "eh_suitability.tif")

############HS
##setwd 
setwd(paleo_path)

##ok load rasters 
pwetm_hs <- raster("hs_v1_2_5m\\bio_13.tif")
mdr_hs <- raster("hs_v1_2_5m\\bio_2.tif")
mtdq_hs <- raster("hs_v1_2_5m\\bio_9.tif")
mtwetq_hs <- raster("hs_v1_2_5m\\bio_8.tif")
precip_season_hs <- raster("hs_v1_2_5m\\bio_15.tif")

##now stack the rasters
hs_stack <- stack(pwetm_hs, mdr_hs, mtdq_hs, mtwetq_hs, 
                  precip_season_hs)

##Crop 
hs_stack_crop <- crop(hs_stack, elevation_crop)

##project to raster
hs_project <- projectRaster(hs_stack_crop, crs = projection)

###Name hs
names(hs_project) <- var_list

##Now predict 
hs_hsm <- predict(hs_project,butternut_model,
                  n.trees= tree_number,type='response')
##set wd
setwd(worldclim_path)

##write out HS HSM 
writeRaster(hs_hsm, "hs_hsm.tif")
writeRaster(hs_hsm > 0.63, "hs_suitability.tif")

############LH HSM
setwd(paleo_path)

##ok load rasters 
pwetm_lh <- raster("lh_v1_2_5m\\bio_13.tif")
mdr_lh <- raster("lh_v1_2_5m\\bio_2.tif")
mtdq_lh <- raster("lh_v1_2_5m\\bio_9.tif")
mtwetq_lh <- raster("lh_v1_2_5m\\bio_8.tif")
precip_season_lh <- raster("lh_v1_2_5m\\bio_15.tif")

##now stack the rasters
lh_stack <- stack(pwetm_lh, mdr_lh, mtdq_lh, mtwetq_lh, 
                  precip_season_lh)
##Crop 
lh_stack_crop <- crop(lh_stack, elevation_crop)

##project to raster
lh_project <- projectRaster(lh_stack_crop, crs = projection)

###Name ba
names(lh_project) <- var_list

##Now predict 
lh_hsm <- predict(lh_project,butternut_model,
                  n.trees= tree_number,type='response')
##set wd
setwd(worldclim_path)

##write out BA HSM 
writeRaster(lh_hsm, "lh_hsm.tif")
writeRaster(lh_hsm > 0.63, "lh_suitability.tif")

############YDS HSM
setwd(paleo_path)

##ok load rasters 
pwetm_yds <- raster("yds_v1_2_5m\\bio_13.tif")
mdr_yds <- raster("yds_v1_2_5m\\bio_2.tif")
mtdq_yds <- raster("yds_v1_2_5m\\bio_9.tif")
mtwetq_yds <- raster("yds_v1_2_5m\\bio_8.tif")
precip_season_yds <- raster("yds_v1_2_5m\\bio_15.tif")

##now stack the rasters
yds_stack <- stack(pwetm_yds, mdr_yds, mtdq_yds, mtwetq_yds, 
                  precip_season_yds)
##Crop 
yds_stack_crop <- crop(yds_stack, elevation_crop)

##project to raster
yds_project <- projectRaster(yds_stack_crop, crs = projection)

###Name yds hsm
names(yds_project) <- var_list

##Now predict 
yds_hsm <- predict(yds_project,butternut_model,
                  n.trees= tree_number,type='response')
##set wd
setwd(worldclim_path)

##write out BA HSM 
writeRaster(yds_hsm, "yds_hsm.tif")
writeRaster(yds_hsm > 0.63, "yds_suitability.tif")

###pdf comparing all habitat suitability plots
setwd(worldclim_only)
pdf("HSM_comparison_worldclim_only.pdf", width = 10, height = 10)
par(mfrow = c(2,2))
plot(lgm_hsm, main = "Butternut Habitat Suitability at the LGM (22000 YBP)")
plot(mid_hol_hsm, main = "Butternut Habitat Suitability in the Mid-Holocene (6000 YBP)")
plot(butternut_prediction_map, main = "Butternut Habitat Suitability in the Prsent (1970-2000)")
dev.off()

pdf("HSM_lig_worldclim_only.pdf", width = 10, height = 10)
plot(lig_hsm, main = "Butternut Habitat Suitability in the Last Interglacial Period (130,000 YBP)")
dev.off()

###############Run some stats
library(dataMaid)

quartiles(hsm_performance_pa[hsm_performance_pa$PA == 1,][,1])

###try plotting 
par(mfrow = c(1,2))
plot(butternut_prediction_map > 0.63)
plot(lig_hsm > 0.63)
##transform everything else? 
butternut_prediction_map_proj <- projectRaster(butternut_prediction_map, crs = "+proj=longlat +ellps=WGS84 +datum=WGS84")

###get map
butternut_map <- getMap(resolution = "low", projection = projection)

##project a bunch of rasters
butternut_prediction_map_proj <- projectRaster(butternut_prediction_map,
                                               crs = "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")
##LIG hsm projection
lig_proj <- projectRaster(lig_hsm, butternut_prediction_map_proj)

##mid-hol
mid_hol_proj <- projectRaster(mid_hol_hsm, butternut_prediction_map_proj)

##LGM 
lgm_proj <- projectRaster(lgm_hsm, butternut_prediction_map_proj)

###write out rasters
writeRaster(butternut_prediction_map_proj,paste0(worldclim_only, "present_hsm_project.tif"))
writeRaster(lgm_proj,paste0(worldclim_only, "lgm_hsm_project.tif"))
writeRaster(mid_hol_proj, paste0(worldclim_only, "mid_hol_hsm_project.tif"))
writeRaster(lig_proj, paste0(worldclim_only, "lig_hsm_project.tif"))

##write raster
writeRaster(present_occurrence_raster, paste0(worldclim_only, "present_occurrence_raster.tif"))
writeRaster(lgm_presence_raster, paste0(worldclim_only, "lgm_presence_raster.tif"))
writeRaster(mid_hol_presence, paste0(worldclim_only, "mid_hol_presence.tif"))
writeRaster(lig_presence, paste0(worldclim_only, "lig_presence.tif"))
