##Based on code generated by Peter Breslin and Fabio Suzart de Albuquerque (ASU)

######################################################################
########################### Libraries ################################
######################################################################

library(raster)
library(sp)
library(sf)
library(rworldmap)
library(rgdal)
library(spdep)
library(rgeos)
library(dismo)
library(gbm)
library(AUC)
library(ggplot2)
library(plyr)
library(HH)
library(ltm)
library(geosphere)

##load data points
setwd("G:\\Shared drives\\Emily_Schumacher\\SDMs")
worldclim_only <- "G:\\Shared drives\\Emily_Schumacher\\SDMs\\worldclim_only_SDM\\"

##read in occurrence records
butternut_presence <- read.csv("InputFiles\\Points\\butternut_presence.csv")
butternut_presence <- butternut_presence[,-1]

##set limits
min_lon <- min(butternut_presence$Longitude)
max_lon <- max(butternut_presence$Longitude)
min_lat <- min(butternut_presence$Latitude)
max_lat <- max(butternut_presence$Latitude)

##turns coordinates into Spatial Points
coordinates(butternut_presence) <- c('Longitude', 'Latitude')
proj4string(butternut_presence) <- CRS("+proj=longlat +ellps=WGS84 +datum=WGS84")

######################################################################
######## Project and Remove Spatial Autocorrelation ##################
######################################################################

##Projection
projection <- c("+proj=aea +lat_1=20 +lat_2=60 +lat_0=40 +lon_0=-96 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs")

##Project to Albers Equal Area Conic 
butternut_presence_2 <- spTransform(butternut_presence, CRS(paste0(projection)))

##First remove points at the exact same place
butternut_presence_2 <- remove.duplicates(butternut_presence_2)

##First we need to reduce spatial autocorrelation

#####100 meters
points_matrix <- gWithinDistance(butternut_presence_2, dist = .00086206895, byid = TRUE)
#####300 meters
points_matrix <- gWithinDistance(butternut_presence_2, dist = .00258620685, byid = TRUE)
######500 m
points_matrix <- gWithinDistance(butternut_presence_2, dist = .0043103448, byid = TRUE)
#####1 km
points_matrix <- gWithinDistance(butternut_presence_2, dist = .0086206897, byid = TRUE)
####2km
points_matrix <- gWithinDistance(butternut_presence_2, dist = .0172413794, byid = TRUE)

##create tri matrix with NAs for bottom rows
points_matrix[lower.tri(points_matrix, diag=TRUE)] <- NA

##now determine where points within 1 km are 
auto_cols <- colSums(points_matrix, na.rm=TRUE) == 0

##now subset the original data by this 
occurrence_wo_auto <- butternut_presence[auto_cols,]

##convert to a data frame
occurrence_no_auto <- data.frame(occurrence_wo_auto)

##occurrence no autocorrelation write out 
write.csv(occurrence_no_auto, paste0(worldclim_only, "\\occurrence_no_auto_noproj.csv"))

##plot extent and occurrence without auto
extent_raster <- raster("G:\\Shared drives\\Emily_Schumacher\\SDMs\\InputFiles\\elevation_extent.tif")

####write out points


##Check to make sure extents align
pdf("G:\\Shared drives\\Emily_Schumacher\\SDMs\\InputFiles\\extent_pointsnoauto.pdf")
plot(extent_raster)
points(butternut_presence)
dev.off()

